name: PR Validation

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/_python-ci.yml
    with:
      python-version: '3.13'

  docker-build:
    name: Docker build (no push)
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/webserver-app-backend
          tags: |
            type=sha,format=short
            type=ref,event=pr
            type=raw,value=${{ github.ref_name }}

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
