name: PR Validation

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"

permissions:
  contents: read

jobs:
  docker-build:
    name: Docker build (no push)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/webserver-app-back
          tags: |
            type=sha,format=short
            type=raw,value={{date 'YYYYMMDD-HHmmss' tz='UTC'}}

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
