name: PR Validation

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - "feature/**"
      - "bugfix/**"
      - "hotfix/**"

permissions:
  contents: read

jobs:
  python-lint-and-test:
    name: Python Linting and Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e ".[dev]"

      - name: Run ruff linter
        run: ruff check .

      - name: Run ruff formatter check
        run: ruff format --check .

      - name: Run mypy type checker
        run: mypy .

      - name: Run unit tests with coverage
        run: pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
