name: Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    name: Build & Push Docker
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{  github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute dev tag
        id: vars
        run: echo "DEV_TAG=dev-$(date -u +%Y%m%d-%H%M%S)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/webserver-app-back
          tags: |
            type=sha,format=short
            type=raw,value={{date 'YYYYMMDD-HHmmss' tz='UTC'}}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          tags: |
            ${{ steps.meta.outputs.tags }}
            ghcr.io/${{ github.repository_owner }}/webserver-app-back:${{ steps.vars.outputs.DEV_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
